### ISSUE TITLE
Wine 7.0 with WoW64 support

### ISSUE THREAD

**Issue by hmtheboy154** [nhubaotruong/league-of-legends-linux-garena-script#27] opened 2022-01-20 01:57 UTC
So Wine 7.0 just announced and in the announcement page they talked about WoW64 support
https://www.winehq.org/announce/7.0
```
- The 64-bit Windows-on-Windows (WoW64) architecture is implemented, and
  supports running a 32-bit Windows application inside a 64-bit Unix host
  process, using thunks to map 32-bit NT system calls to the 64-bit NTDLL.

- WoW64 thunks are implemented for most Unix libraries, enabling a 32-bit PE
  module to call a 64-bit Unix library. Once the remaining modules are
  converted to PE, this will make it possible to run 32-bit applications
  without installing 32-bit Unix libraries.
```

Does that mean running the game (64bit) with Garena client (32bit) will be easier since both 64bit and 32bit can run on the same 64bit Unix host ?

**Comment by nhubaotruong** [comment] 2022-01-20 02:01
We won't know until we try it out, currently the problem is LOL requires some Windows syscall that wine haven't support, hence we need to use a patched wine. Don't know if the thing is in upstream or not

**Comment by nhubaotruong** [comment] 2022-01-23 15:54
Hey I've tried the script from lutris: https://lutris.net/games/garena/. For me it has a kind of problem that the client doesn't reappear after a game

**Comment by hmtheboy154** [comment] 2022-01-27 16:02
> We won't know until we try it out, currently the problem is LOL requires some Windows syscall that wine haven't support, hence we need to use a patched wine. Don't know if the thing is in upstream or not
well I don't think they added the patch to wine
but at least Wine GE have it
https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/7.0-GE-1-LoL

**Comment by nhubaotruong** [comment] 2022-01-27 16:06
https://lutris.net/games/garena/
I see that this guy already updated Garena install script. Have you tried it yet ?

**Comment by hmtheboy154** [comment] 2022-01-27 16:18
No this is not my script

**Comment by nhubaotruong** [comment] 2022-01-27 16:24
I meant have you tried using the script from lutris :smile_cat:

**Comment by nhubaotruong** [comment] 2022-03-24 15:39
I'm gonna close this since there's no discussion, feel free to reopen

**Closed by nhubaotruong** 2022-03-24 15:39 UTC
